// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import path from "path";
import { defineConfig } from "prisma/config";

// .env.local 우선 로드
dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });
// .env도 로드 (fallback)
dotenv.config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI(db push/migrate)는 Direct(5432) 우선 — Pooler(6543, PgBouncer transaction)는 DDL 불가.
    // 런타임 PrismaClient는 본 설정을 보지 않고 자체적으로 env DATABASE_URL을 읽으므로 무관.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
